2025-10-02 14:39:09 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-98' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> exception=AttributeError("'AttributeError' object has no attribute 'empty'")>
Traceback (most recent call last):
  File "G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py", line 136, in _render_timer_loop
    if task_status_df.empty:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AttributeError' object has no attribute 'empty'
2025-10-02 20:55:55 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-130' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 20:55:55 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-129' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:240> wait_for=<Future cancelled>>
2025-10-02 20:59:06 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 20:59:06 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-39' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 20:59:06 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-38' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:240> wait_for=<Future cancelled>>
2025-10-02 21:05:50 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-41' coro=<_render_timer_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:191> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:05:50 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<_render_timer_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:156> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:05:50 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-40' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:240> wait_for=<Future cancelled>>
2025-10-02 21:07:17 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:07:17 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-41' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:07:17 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-40' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:269> wait_for=<Future cancelled>>
2025-10-02 21:14:46 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-54' coro=<_render_timer_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:191> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:14:46 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-53' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:269> wait_for=<Future cancelled>>
2025-10-02 21:18:10 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-78' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:18:10 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-77' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:269> wait_for=<Future cancelled>>
2025-10-02 21:22:31 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-118' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:22:31 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-117' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:269> wait_for=<Future cancelled>>
2025-10-02 21:52:21 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-66' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:81> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 21:52:21 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-65' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:218> wait_for=<Future cancelled>>
2025-10-02 22:06:19 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1315, in process_update
    await coroutine
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 159, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_execution.py", line 107, in complete_task_inline
    await query.edit_message_text(
    ...<3 lines>...
    )
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_callbackquery.py", line 268, in edit_message_text
    return await self._get_message().edit_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_message.py", line 4142, in edit_text
    return await self.get_bot().edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<15 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 1735, in edit_message_text
    return await super().edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<15 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4463, in edit_message_text
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 634, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<23 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 819, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 703, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 372, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 732, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 198, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Alpha\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 375, in _request_wrapper
    raise exception
telegram.error.BadRequest: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
2025-10-02 22:24:50 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<_render_timer_loop() done, defined at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:81> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-02 22:24:50 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-27' coro=<_time_tracker_loop() running at G:\FOR ALL BOTS\The_Gap_2\src\handlers\task_handlers\task_timer.py:218> wait_for=<Future cancelled>>
