2025-10-01 10:51:23 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<_render_timer_loop() done, defined at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-01 10:51:23 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-39' coro=<_render_timer_loop() done, defined at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-01 10:51:23 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-38' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:240> wait_for=<Future cancelled>>
2025-10-01 11:14:47 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-99' coro=<_render_timer_loop() done, defined at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:99> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-01 11:14:47 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-98' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:240> wait_for=<Future cancelled>>
2025-10-01 13:32:10 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-38' coro=<_render_timer_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:156> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-01 13:32:10 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-37' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:240> wait_for=<Future cancelled>>
2025-10-01 13:50:40 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-112' coro=<_render_timer_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:156> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-01 13:50:40 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-111' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:240> wait_for=<Future cancelled>>
2025-10-01 14:55:50 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1311, in process_update
    await coroutine
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_execution.py", line 271, in show_task
    await query.edit_message_text(task_info, parse_mode="Markdown", reply_markup=get_task_keyboard())
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_callbackquery.py", line 266, in edit_message_text
    return await self._get_message().edit_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_message.py", line 3904, in edit_text
    return await self.get_bot().edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<15 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 1723, in edit_message_text
    return await super().edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<15 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4294, in edit_message_text
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 630, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<21 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 810, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 698, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 370, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 727, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 197, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 374, in _request_wrapper
    raise exception
telegram.error.BadRequest: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
