2025-10-07 09:46:52 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-115' coro=<_render_timer_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:180> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 09:46:52 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-114' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:218> wait_for=<Future cancelled>>
2025-10-07 11:20:23 - telegram.ext - ERROR - Network Retry Loop (Polling Updates): Invalid token. Aborting retry loop.
Traceback (most recent call last):
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 340, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 670, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4611, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 698, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 370, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 727, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 197, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 374, in _request_wrapper
    raise exception
telegram.error.InvalidToken: Unauthorized
2025-10-07 11:20:26 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Application:8390538420:update_fetcher' coro=<Application._update_fetcher() running at C:\Users\bexultan.kobetay\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py:1228> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 11:22:58 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-69' coro=<_render_timer_loop() done, defined at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:81> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 11:22:58 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-44' coro=<_render_timer_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:145> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 11:22:58 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-68' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:218> wait_for=<Future cancelled>>
2025-10-07 11:28:10 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-51' coro=<_render_timer_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:180> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 11:28:10 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-50' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:218> wait_for=<Future cancelled>>
2025-10-07 14:55:19 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-60' coro=<_render_timer_loop() done, defined at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:81> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 14:55:19 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-43' coro=<_render_timer_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:145> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 14:55:19 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-59' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:218> wait_for=<Future cancelled>>
2025-10-07 15:07:06 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-132' coro=<_render_timer_loop() done, defined at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:81> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-10-07 15:07:06 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task cancelling name='Task-131' coro=<_time_tracker_loop() running at C:\Users\bexultan.kobetay\Desktop\FOR ALL BOTS\The_gap_2\src\handlers\task_handlers\task_timer.py:218> wait_for=<Future cancelled>>
